### ISSUE TITLE
check_text_elements doesn't find all text elements

### ISSUE THREAD

**Issue by flaiker** [abaplint/abaplint#858]
I have a lot of errors regarding text elements that are used but not found.

> Text element "026" not found (check_text_elements)

May be related to function groups and the check not looking in the XML file for the group but for the specific include. Or the cause could be that the elements not found (some are found!) are in a very weird sort order in the xml file. They are listed after the selection screen texts while the ones that are found are listed before the selection screen texts:

```xml
﻿<?xml version="1.0" encoding="utf-8"?>
<abapGit version="v1.0.0">
 <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
  <asx:values>
   <PROGDIR>
    <NAME>/ABC/SAPL...</NAME>
    <DBAPL>S</DBAPL>
    <DBNA>D$</DBNA>
    <SUBC>F</SUBC>
    <APPL>S</APPL>
    <RLOAD>D</RLOAD>
    <FIXPT>X</FIXPT>
    <LDBNAME>D$S</LDBNAME>
    <UCCHECK>X</UCCHECK>
   </PROGDIR>
   <TPOOL>
    <item>
     <ID>I</ID>
     <KEY>001</KEY>
     <ENTRY>My text 001</ENTRY>
     <LENGTH>40</LENGTH>
    </item>
    ...
    <item>
     <ID>I</ID>
     <KEY>025</KEY>
     <ENTRY>My text 025</ENTRY>
     <LENGTH>30</LENGTH>
    </item>
    <item>
     <ID>S</ID>
     <KEY>S_ABC</KEY>
     <ENTRY>.</ENTRY>
     <LENGTH>21</LENGTH>
     <SPLIT>D</SPLIT>
    </item>
    <item>
     <ID>S</ID>
     <KEY>S_DEF</KEY>
     <ENTRY>.</ENTRY>
     <LENGTH>20</LENGTH>
     <SPLIT>D</SPLIT>
    </item>
    <item>
     <ID>I</ID>
     <KEY>026</KEY>
     <ENTRY>My text 025</ENTRY>
     <LENGTH>19</LENGTH>
    </item>
    <item>
     <ID>I</ID>
     <KEY>027</KEY>
     <ENTRY>My text 026</ENTRY>
     <LENGTH>42</LENGTH>
    </item>
    ...
   </TPOOL>
  </asx:values>
 </asx:abap>
</abapGit>
```

And somewhat related I also get the problem mentioned in #745 with lowercase `text` `Keyword should be upper case: "text" (keyword_case)`.

**Comment by larshp** [comment]
yea, function groups are a bit broken

**Comment by larshp** [comment]
some of these might be fixed with the changes done in https://github.com/abaplint/abaplint/issues/844

**Comment by larshp** [comment]
2.32.10 released, can you rerun to see if this error is still present?

**Comment by flaiker** [comment]
Unfortunately the result is still the same.

**Comment by flaiker** [comment]
Might also have to do with the kind of text element reference used in the code? I noticed these were found:

```abap
text-004
```

And these were not:

```abap
'My awesome text'(026)
```

**Comment by larshp** [comment]
can you help reproducing this issue in a public repo?

**Comment by flaiker** [comment]
I was so far unable to reproduce it in a public repo. See here:

https://github.com/flaiker/abaplint-test-text-elements

Might be namespace related? Don't know how to setup a namespace in the developer edition AS ABAP without a developer license. Cannot create public repos in company namespace. :shrug:

**Comment by flaiker** [comment]
I'll update abapGit and abaplint and report back. Might also have been fixed on either side in the meantime.

**Comment by larshp** [comment]
yea, it might be namespace related

**Comment by flaiker** [comment]
Latest abapGit build doesn't report any diffs for the related function groups. I manually moved the sort order of the tpool items in the xml in the public repo but that didn't cause abaplint to fail either.

**Comment by flaiker** [comment]
Does this help in any way? (It might also just fail because for function groups it needs the main program in memory as well.)

https://github.com/flaiker/abaplint/runs/747030813?check_suite_focus=true

>   1) Rule: check_text_elements
>        test 1:
> 
>       AssertionError: expected 1 to equal 0
>       + expected - actual
> 
>       -1
>       +0
>       
>       at Context.<anonymous> (test/rules/check_text_elements.ts:53:30)
>       at processImmediate (internal/timers.js:456:21)
> 
> 
> 
> npm ERR! Test failed.  See above for more details.
> npm ERR! Test failed.  See above for more details.
> ##[error]Process completed with exit code 1.

https://github.com/flaiker/abaplint/commit/0b4c4682174124280c4e81dc4703ac1ac4d5e017

**Comment by larshp** [comment]
would like a real world example, its difficult to build as a unit test, as there are multiple things that must match

**Comment by larshp** [comment]
but I'll probably take a look anyhow
